version: '3'

services:
  php:
    build: .
    ports:
      - 8080:80
    links:
      - db
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./public:/var/www/html

  db:
    image: mariadb:10.2
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: plokijuh
      MYSQL_USER: dev
      MYSQL_PASSWORD: plokijuh
      MYSQL_DATABASE: hiring
